-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.candidates
(
    id integer NOT NULL,
    first_name character varying(35) NOT NULL,
    last_name character varying(35) NOT NULL,
    identification_number character varying(11) NOT NULL,
    birth_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates_cv
(
    id integer NOT NULL,
    github_address character varying(1000) NOT NULL,
    linkedin_address character varying(1000) NOT NULL,
    cover_letter character varying(5000) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates_cv_foreign_languages
(
    id integer NOT NULL,
    name character varying(1000) NOT NULL,
    level character varying(1000) NOT NULL,
    candidates_cv_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates_cv_job_experiences
(
    id integer NOT NULL,
    job_location_name character varying(10000) NOT NULL,
    job_position character varying(1000) NOT NULL,
    year_of_employment character varying(1000) NOT NULL,
    year_off character varying(1000),
    candidates_cv_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates_cv_tech_tools
(
    id integer NOT NULL,
    name character varying(1000) NOT NULL,
    candidates_cv_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates_cv_universities
(
    id integer NOT NULL,
    universty_name character varying(1000) NOT NULL,
    universty_faculty character varying(1000) NOT NULL,
    application_year character varying(100) NOT NULL,
    graduation_year character varying(100),
    candidates_cv_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employee_confirms
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employee_confirms_employers
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    employer_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    first_name character varying(35) NOT NULL,
    last_name character varying(35) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employer_phones
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id integer NOT NULL,
    phone_number character varying(12) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL,
    company_name character varying(255) NOT NULL,
    web_address character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_titles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 4 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_vacancy
(
    id integer NOT NULL,
    job_position character varying(250) NOT NULL,
    job_description character varying(1000) NOT NULL,
    city_info character varying(1500) NOT NULL,
    salary_min integer NOT NULL,
    salary_max integer NOT NULL,
    open_position_number integer NOT NULL,
    release_date date NOT NULL,
    application_deadline date NOT NULL,
    is_active boolean NOT NULL,
    company_name character varying(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email_address character varying(320) NOT NULL,
    password character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification_codes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    code character varying(38) NOT NULL,
    is_verified boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification_codes_candidates
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    candidate_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification_codes_employers
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    employer_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.candidates_cv_foreign_languages
    ADD FOREIGN KEY (candidates_cv_id)
    REFERENCES public.candidates_cv (id)
    NOT VALID;


ALTER TABLE public.candidates_cv_job_experiences
    ADD FOREIGN KEY (candidates_cv_id)
    REFERENCES public.candidates_cv (id)
    NOT VALID;


ALTER TABLE public.candidates_cv_tech_tools
    ADD FOREIGN KEY (candidates_cv_id)
    REFERENCES public.candidates_cv (id)
    NOT VALID;


ALTER TABLE public.candidates_cv_universities
    ADD FOREIGN KEY (candidates_cv_id)
    REFERENCES public.candidates_cv (id)
    NOT VALID;


ALTER TABLE public.employee_confirms
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (id)
    NOT VALID;


ALTER TABLE public.employee_confirms_employers
    ADD FOREIGN KEY (id)
    REFERENCES public.employee_confirms (id)
    NOT VALID;


ALTER TABLE public.employee_confirms_employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employer_phones
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_vacancy
    ADD FOREIGN KEY (company_name)
    REFERENCES public.employers (company_name)
    NOT VALID;


ALTER TABLE public.job_vacancy
    ADD FOREIGN KEY (id)
    REFERENCES public.job_titles (id)
    NOT VALID;


ALTER TABLE public.verification_codes_candidates
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.verification_codes_candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.verification_codes (id)
    NOT VALID;


ALTER TABLE public.verification_codes_employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.verification_codes_employers
    ADD FOREIGN KEY (id)
    REFERENCES public.verification_codes (id)
    NOT VALID;

END;